name: Broken link check for repo
on:
  workflow_dispatch:

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links in repo
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker # Should always pull the latest release version
        with:
          # Required:
          url: "https://github.com/swirlai/swirl-search"
          # optional:
          honorRobotExclusions: false
          ignorePatterns: "github,google,localhost,opensource"
          recursiveLinks: true # Check all URLs on all reachable pages (could take a while)
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
